/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Articulo__factory } from "./Articulo__factory";
export { ArticuloFactory__factory } from "./ArticuloFactory__factory";
