/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Articulo } from "./Articulo";
export type { ArticuloFactory } from "./ArticuloFactory";
export * as factories from "./factories";
export { Articulo__factory } from "./factories/Articulo__factory";
export { ArticuloFactory__factory } from "./factories/ArticuloFactory__factory";
